# -*- coding: utf-8 -*-
"""CSE110,ASSIGNMENT5(will change later).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DrHy3RQ5MNfosmfVqzTV7N691hwooC3w
"""

#task1
a_tuple = ("The Institute", ("Best Mystery & Thriller", "The Silent Patient", 68821), 75717,[1, 2, 3, 400, 5, 6, 7], ("Best Fiction", "The Testaments", 98291))
print(a_tuple[3][3])

#task2
given_tuple=(-10, 20, 40)
new_tuple=given_tuple[2:-2:]
print(new_tuple)

#task3
book_info = (("Best Mystery & Thriller","The Silent Patient",68,821),("Best Horror","The Institute",75,717),("Best History & Biography","The five",31,783 ),("Best Fiction","The Testaments",98,291))

print("size of the tuple:",len(book_info))
for i in book_info:
    print(i,end="")
    print()

#task4
book_info = (("Best Mystery & Thriller","The Silent Patient",68821),("Best Horror","The Institute",75717),("Best History & Biography","The five",31783 ),("Best Fiction","The Testaments",98291))

print(book_info[0][1],"won the","'"+book_info[0][0]+"'","category with",book_info[0][2],"votes")

#task5
Guple=(10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
a=int(input())
print(Guple.count(a))

given_tuple=(10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
n=int(input())

count=0
for i in given_tuple:
    if i==n:
        count+=1
print(count)

#task6
given_tuple=('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
list1=list(given_tuple)

list1.reverse()
newtp=tuple(list1)

print(newtp)

given_tuple=('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
list2=[]
for i in given_tuple:
    list2.append(i)
print(list2)
list2.reverse()
ne=tuple(list2)
print(ne)

#task7
g1={'Harry':15, 'Draco':8, 'Nevil':19}
g2={'Ginie':18, 'Luna': 14}

marks={}

marks.update(g1)
marks.update(g2)
print(marks)

#task8
dic={}
n=int(input())
for i in range(n):
    key_input=input()
    value_input=int(input())
    dic.update({key_input:value_input})


sum=0

for i in dic:
    sum+=dic[i]
print(sum/n)

#task9
exam_marks = {'Cierra Vega': 175, 'Alden Cantrell': 200, 'Kierra Gentry': 165, 'Pierre Cox': 190}
n=int(input())
new={}
for i,j in exam_marks.items():
    if j>=n:
        new.update({i:j})
print(new)

#task10

given={'sci fi': 12, 'mystery': 15, 'horror': 8, 'mythology': 10, 'young_adult': 4, 'adventure':14}
list1=list(given.keys())
print(list1)
list2=list(given.values())
maxx=list2[0]

for i in list2:
    if i>maxx:
        maxx=i
print(maxx)

#task11
n=input().lower()
dic={}

for i in n:
    if i in dic:
        dic[i]+=1
    else:
        dic[i]=1

print(dic)

#task12
dict_1 = {'A': [1, 2, 3], 'b': ['1', '2'], "c": [4, 5, 6, 7]}
list1=list(dict_1.values())
count=0
for i in list1:
    for j in i:
        count+=1

print(count)

#task13
list_1 = [("a", 1), ("b", 2), ("a", 3), ("b", 1), ("a", 2), ("c", 1)]
list2=[]
list3=[]
for i in list_1:
    a,b=i
    list2.append(a)
    list3.append(b)

dic={}

for i in range(len(list3)):
    dic.append({list2[i]:list3[i]})
print(dic)

list_1 = [("a", 1), ("b", 2), ("a", 3), ("b", 1), ("a", 2), ("c", 1)]
dict1={}
for i in list1:
    if i[0] in dict1.keys():
        dict1[i[0]].append(i[1])
    else:
        x=[i[1]]
        dict1[i[0]]=x
print(dict1)

