# -*- coding: utf-8 -*-
"""22101761_Md Kawser Alam Noman_25_CSE110Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jZVY67j3H_HdW_S1BwblYtLRo-B9yzk9

# CSE110 Lab Assignment 1 (Branching)

This assignment is to guide you to solve basic programming problems in Python. Since this is the first assignment, the first problem is solved for you with explanations. The second problem is partially solved to help you. Please go through them and try to understand each statment. If you can understand the problems and the solutions done for you, you can try to solve the rest of the tasks by yourself.

**<font color='red'>Please maintain variable naming conventions for all the tasks.</font>**\
<font color='red'>When you run your code, please make sure your outputs exactly match the sample outputs for each of the sample inputs given. Check if your code works for other valid inputs not given in the samples.</font>

## Write the Python code for the following problems:

### Task 1

Write the Python code of a program that reads two numbers from the user, and prints their sum, product, and difference.

==========================================================

*Hint: subtract the second number from the first one*

==========================================================

**Example 1:**

**Sample Input:**\
 4\
 5

**Sample Output:**\
Sum = 9\
Product = 20\
Difference = -1

==========================================================

**Example 2:**

**Sample Input:**\
 30\
 2

**Sample Output:**\
Sum = 32\
Product = 60\
Difference = 28

==========================================================

For your explanation, the first question's code is done below. Try relating the block of code with the lessons you have learned and try to understand the significance of each line. You're most welcome to play around with the code. This will strengthen your understanding.
"""

var_1=input('Please enter first number: ')
var_2=input('Please enter second number: ')

print(type(var_1))
print(type(var_2))

var_3=int(var_1)
var_4=int(var_2)

total= var_3 + var_4

product= var_3*var_4

difference= var_3-var_4

print('sum= ',total)
print('product= ', product)
print('difference= ',difference)

#second way

var_1=int(input('please enter first number: '))
var_2=int(input('please enter second number: '))

total= var_1 + var_2
product=var_1*var_2
difference= var_1-var_2

print('sum =',total)
print('product =',product)
print('difference =',difference)

"""### Task 2

Write the Python code of a program that reads the radius of a circle and prints its circumference and area.

==========================================================

*hint(1): we may import math and then use **math.pi** for getting the value of pi.\
For details, we can read from https://docs.python.org/3/library/math.html*

*hint(2): we can import math and use the math function for making squares with math.pow(number, power) or we can simply use the power operator. For example:  S**2.*

==========================================================

**Example 1:**

**Sample Input:**\
4

**Sample Output:**\
Area is 50.26548245743669\
Circumference is 25.132741228718345

==========================================================

**Example 2:**

**Sample Input:**\
3.5

**Sample Output:**\
Area is 38.48451000647496\
Circumference is 21.991148575128552

==========================================================

For your understanding, the the first part of the question(area calculation) is done below.
"""

import math

radius = float(input('Please enter the radius value:'))

#1st way
area= math.pi * radius**2
print('area=',area)
#second way

area= math.pi * math.pow(radius, 2)
print('area=',area)
#third way

area= math.pi * radius* radius
print('area=',area)

#finding circumference

circumference= 2*math.pi*radius

print('circumference=',circumference)

"""### Task 3

Write the Python code of a program that reads two numbers from the user. The program should then print "First is greater" if the first number is greater, "Second is greater" if the second number is greater, and "The numbers are equal" otherwise.

==========================================================

**Sample Input 1:**\
7\
3

**Sample Output 1:**\
First is greater

==========================================================

**Sample Input 2:**\
-33\
-3

**Sample Output 2:**\
Second is greater

==========================================================

**Sample Input 1:**\
11\
11

**Sample Output 1:**\
The numbers are equal

"""

#todo
#as someone can input float variable as their number ,that's why we use float.
First =float(input('enter your first number'))
Second =float(input('enter your second number'))

if (First>Second):
    print('First is greater')

elif (Second>First) :
    print('Second is greater')

else:
    print('The numbers are equal')

"""### Task 4

Write the Python code of a program that reads two numbers, subtracts the smaller number from the larger one, and prints the result.

*Hint: First, we may check which number is greater*

==========================================================

**Sample Input 1:**\
-40\
-4

**Sample Output 1:**\
36

**Explanation:** -4 > -40 so -4 - (-40) = -4 + 40 = 36

==========================================================

**Sample Input 2:**\
6\
2

**Sample Output 2:**\
4

==========================================================


**Sample Input 3:**\
5\
5

**Sample Output 3:**\
0

"""

#todo
x= float(input('enter a number '))
y= float(input('enter another number '))
a=x-y
b=y-x
if (x>=y):
    print(a)
else:
    print(b)

"""### Task 5

Write the Python code of a program that reads a number, and prints "The number is even" or "The number is odd", depending on whether the number is even or odd.

*hint(1): we may use the modulus (%) operator to check for even or odd*

*hint(2): we can consider the number to be an integer*

==========================================================

**Sample Input 1:**\
7

**Sample Output 1:**\
The number is odd

==========================================================

**Sample Input 2:**\
10

**Sample Output 2:**\
The number is even

==========================================================

**Sample Input 3:**\
-44

**Sample Output 3:**\
The number is even

"""

#todo

x =int(input('Enter an integer number'))

if (x%2 ==0):
    print('The number is even')

else:
    print('The number is odd')

"""### Task 6

Write the Python code of a program that reads an integer as input from the user, and prints the integer if it is a multiple of **2 OR 5** and prints "Not a multiple of 2 OR 5" otherwise.

For example, 2, 4, 5, 6, 8, 10, 12, 14, 15, 16, 18, 20, 22 … i.e. this includes multiples of 2 only, multiples of 5 only and multiples of 2 and 5 both.

==========================================================

*hint(1): we may use the modulus (%) operator for checking the divisibility*

*hint(2): we can consider the number to be an integer*

==========================================================

**Sample Input 1:**\
5

**Sample Output 1:**\
5

==========================================================

**Sample Input 2:**\
10

**Sample Output 2:**\
10

==========================================================

**Sample Input 3:**\
3

**Sample Output 3:**\
Not a multiple of 2 OR 5

"""

#todo
x= int(input('Please enter an integer '))

if(x%2 ==0):
    print(x)
elif(x%5 ==0):
    print(x)
else:
    print('Not a multiple of 2 OR 5')

"""### Task 7
Write the Python code of a program that reads an integer, and prints the integer  it is a multiple of **either 2 or 5 but not both.** If the number is a multiple of 2 and 5 both, then print "Multiple of 2 and 5 both". For all other numbers, the program prints "Not a multiple we want".

For example, 2, 4, 5, 6, 8, 12, 14, 15, 16, 18, 22 … i.e. this includes multiples of 2 only and multiples of 5 only, NOT multiples of 2 and 5 both or other numbers.

==========================================================

*hint(1): we may use the modulus (%) operator for checking the divisibility*

*hint(2): we can consider the number to be an integer*

==========================================================

**Sample Input 1:**\
6

**Sample Output 1:**\
6

==========================================================

**Sample Input 2:**\
15

**Sample Output 2:**\
15

==========================================================

**Sample Input 3:**\
10

**Sample Output 3:**\
Multiple of 2 and 5 both

==========================================================

**Sample Input 4:**\
17

**Sample Output 4:**\
Not a multiple we want
"""

#todo
x= int(input('Please enter an integer '))

if(x%2==0 and x%5 ==0):
    print('Multiple of 2 and 5 both')
elif(x%2==0 or x%5==0):
    print(x)
else:
    print('Not a multiple we want')

"""### Task 8
Write the Python code of a program that reads an integer, and prints the integer if it is a multiple of **2 AND 5** and prints "Not multiple of 2 and 5 both" otherwise.

==========================================================

For example, 10, 20, 30, 40, 50 … i.e. this only includes numbers which are multiples of both 2 and 5.

*hint(1): we may use the modulus (%) operator for checking the divisibility*

*hint(2): we can consider the number to be an integer*

==========================================================

**Sample Input 1:**\
30

**Sample Output 1:**\
30

==========================================================

**Sample Input 2:**\
15

**Sample Output 2:**\
Not multiple of 2 and 5 both


==========================================================

**Sample Input 3:**\
6

**Sample Output 3:**\
Not multiple of 2 and 5 both
"""

#todo
x= int(input('Please enter an integer '))

if(x%2==0 and x%5 ==0):
    print(x)
else:
    print('Not multiple of 2 and 5 both')

"""### Task 9
Write the Python code of a program that finds the number of hours, minutes, and seconds in a **given number of seconds.** The number of seconds is taken as input from the user.

==========================================================

*hint(1): we may consider our user input to be an integer value and use // and % operators to solve the problem*

*hint(2): 1 hour = 60 mins = 3600 seconds* and *1 min = 60 seconds*

==========================================================

**Sample Input 1:**\
10000

**Sample Output 1:**\
Hours: 2  Minutes: 46  Seconds: 40

**Explanation:**\
10000 seconds = 10000 // 3600 = 2 hours and 10000 % 3600 = 2800 seconds.\
Then again, 2800 // 60 = 46 minutes and 2800 % 60 = 40 seconds.\
And hence we have arrived at our answer.

==========================================================

**Sample Input 2:**\
500

**Sample Output 2:**\
Hours: 0  Minutes: 8  Seconds: 20

"""

#todo
x=int(input('enter number '))
Hours=x//3600
Minutes=(x%3600)//60
Seconds=(x%3600)%60
if (x>0):
    print('Hours:',Hours)
    print('Minutes:',Minutes)
    print('Seconds:',Seconds)

else:
    print('time value can not be negative')

"""### Task 10

Write a Python program to compute and display a person’s weekly salary as determined by the following conditions:

* If the hours worked is less than or equal to 40, then the person receives Tk 200 per hour.
* If the hours worked is greater than 40, then the person receives Tk 8000 plus Tk 300 for each hour worked over 40 hours.

The program should request the hours worked as an input from the user and display the salary as output. You need to make sure that user input is valid. For example, a person cannot work for -5 hours or more than 168 hours in a week. So, the valid hours range is 0 to 168. For invalid hours, print outputs as given in the samples below.

==========================================================

*Hint: you can consider the hour (user input) to be an integer*

==========================================================

**Sample Input 1:**\
100

**Sample Output 1:**\
26000

**Explanation:** Since, the number of hours worked is 100 > 40, therefore salary = 8000 + (100 - 40) * 300 = 26000.

==========================================================

**Sample Input 2:**\
30

**Sample Output 2:**\
6000

**Explanation:** Since, the number of hours worked is 30 < 40, therefore salary = 30 * 200 = 6000.

==========================================================

**Sample Input 3:**\
-30

**Sample Output 3:**\
Hour cannot be negative

==========================================================

**Sample Input 4:**\
170

**Sample Output 4:**\
Impossible to work more than 168 hours weekly
"""

#todo
hours=int(input('enter your working hour '))
salary_1=hours*200
h=hours-40
salary_2=h*300+8000
if(hours>=0 and hours<=168):
    if(hours<=40):
        print(salary_1)
    else:
        print(salary_2)
elif(hours>168):
    print('Impossible to work more than 168 hours weekly')
else:
    print('Hour cannot be negative')

"""### Task 11
Suppose the following expressions are used to calculate the values of L for different values of S:

$L =  3000-125S^2$
if     $S<100$

$ L =  \frac{12000}{4+S^2/14900}$
if     $S\geq100$

Write the Python code of a program that reads a value of S and then calculates the value of L.

==========================================================

*hint(1): you can import math and use math function for making squares with math.pow(number, power) or you can simply write S ** 2.*

*hint(2): the value of S(user input) will be an integer*

==========================================================

**Sample Input 1:**\
120

**Sample Output 1:**\
2416.2162162162163

**Explanation:** Since S (user input) given here is 120 >= 100, so L = 12000 / (4 + (120 * 120)/14900) = 2416.2162162162163

==========================================================

**Sample Input 2:**\
3

**Sample Output 2:**\
1875

**Explanation:** Since S (user input) given here is 3 < 100, so L = 3000 - 125 * 3 * 3 = 1875

"""

#todo
import math
S=float(input('enter a value'))
if(S<100):
    print(3000-125*S**2)
else:
    print(12000/(4+(S**2/14900)))

"""### Task 12

Write a Python program that takes an hour from the user as input and tells it is time for which meal.

•	The user will input the number in a 24-hour format. So, 14 means 2 pm, 3 means 3 am, 18 means 6 pm, etc.\
•	Valid inputs are 0 to 23. Inputs less than 0 or more than 23 are invalid in 24-hour clock.\
•	Assume, input will be whole numbers. For example, 3.5 will NOT be given as input.

==========================================================

**Input range: Message to be printed**\
4 to 6: Breakfast\
12 to 13: Lunch\
16 to 17: Snacks\
19 to 20: Dinner\
For all other valid inputs, say "Patience is a virtue"\
For all other invalid inputs, say "Wrong time"

==========================================================

For example,\
If the user enters 4, your program should print the message "Breakfast".\
If the user enters 5, your program should print the message "Breakfast".\
If the user enters 6, your program should print the message "Breakfast".\
If the user enters 0, your program should print the message "Patience is a virtue".\
If the user enters 1, your program should print the message "Patience is a virtue".\
If the user enters 18, your program should print the message "Patience is a virtue".\
If the user enters 23, your program should print the message "Patience is a virtue".\
If the user enters 24, your program should print the message "Wrong Time".\
If the user enters -1, your program should print the message "Wrong Time".\
If the user enters 27, your program should print the message "Wrong time".

==========================================================

Hints: You can use nested conditionals (if-else) or chained conditions (if-elif-else) to solve this problem.


"""

#todo
x=int(input("enter time to check mealtime"))
a=[4,5,6]
b=[12,13]
c=[16,17]
d=[19,20]

if(x>=0 and x<=23):
    if(x in a or x in b or x in c or x in d):
        if(x in a):
            print("Breakfast")
        elif(x in b):
            print("Lunch")
        elif(x in c):
            print("Snacks")
        else:
            print("Dinner")
    else:
        print("Patience is virtue")
else:
    print("Wrong time")

"""### Task 13

Write the Python code of a program that reads a student’s mark for a single subject, and prints out the corresponding grade for that mark. The mark ranges and corresponding grades are shown in the table below. You need to make sure that the mark is valid. For example, a student cannot receive -5 or 110 marks. So, the valid marks range is 0 to 100.

*hint(1): you can consider the number to be an integer*

*hint(2): this problem can be solved in two ways: top-down (starts from A) and bottom-up (starts from F)*


| Marks | Grade|
| --- | --- |
|90 or above| A |
|  |  |
|80-89| B |
|  |  |
|70-79| C |
|  |  |
|60-69| D |
|  |  |
|50-59| E |
|  |  |
|Below 50| F |
|  |  |

"""

#todo
a=int(input('enter your marks'))
if(a>=0 and a<=100):
    if(a<50):
        print('F')
    elif(a>=50 and a<60):
        print('E')
    elif(a>=60 and a<70):
        print('D')
    elif(a>=70 and a<80):
        print('C')
    elif(a>=80 and a<90):
        print('B')
    else:
        print('A')
else:
    print('invalid entry')

"""### Task 14

You are designing a robot that can calculate the temperature and guess the season. Write a Python program that takes a number as input, representing the temperature in degrees Fahrenheit, and converts it into degrees Celsius, and then prints the season based on the following table:


| Temperature (degrees Celsius) | Season|
| --- | --- |
|Less than 20 degrees| Winter |
|  |  |
|Between 20 degrees and 25 degrees (inclusive)| Autumn |
|  |  |
|Greater than 25 degrees and less than 30 degrees| Spring |
|  |  |
|Greater than or equal to 30 degrees| Summer |
|  |  |


Use the following formula to convert the temperature:\
(degrees Celsius) = ((degrees Fahrenheit) - 32) * 0.56

==========================================================

**Sample Input 1:**\
82

**Sample Output 1:**\
28 degrees C\
Spring

**Explanation:** The temperature in Celsius is (82 - 32) * 0.56 = 28 degrees, which is printed. This is between 25 and 30 degrees, so “Spring” is printed after that.

==========================================================

**Sample Input 2:**\
32

**Sample Output 2:**\
0 degrees C\
Winter

**Explanation:** The temperature in Celsius is (32 - 32) * 0.56 = 0 degrees, which is printed. This is less than 20 degrees, so “Winter” is printed after that.

==========================================================

**Sample Input 3:**\
76

**Sample Output 3:**\
24.64 degrees C\
Autumn

**Explanation:** The temperature in Celsius is (76 - 32) * 0.56 = 24.64 degrees, which is printed. This is between 20 degrees and 25 degrees (inclusive), so “Autumn” is printed after that.

==========================================================

**Sample Input 4:**\
77

**Sample Output 3:**\
25.2 degrees C\
Spring

**Explanation:** The temperature in Celsius is (77 - 32) * 0.56 = 25.2 degrees, which is printed. This is greater than 25 degrees and less than 30 degrees, so “Spring” is printed after that.

"""

#todo
degrees_Fahrenheit=float(input('enter temperature in degrees Fahrenheit '))
degrees_Celsius = (degrees_Fahrenheit - 32) * 0.56

if ((degrees_Celsius)<=55 and (degrees_Celsius)>=-35):
    if (degrees_Celsius<20):
        print(degrees_Celsius ,'degrees C')
        print("Winter")
    elif (degrees_Celsius>=20 and degrees_Celsius<=25):
        print(degrees_Celsius ,'degrees C')
        print("Autumn")

    elif (degrees_Celsius>25 and degrees_Celsius<30):
        print(degrees_Celsius ,'degrees C')
        print("Spring")

    elif((degrees_Celsius)>= 30):
        print(degrees_Celsius ,'degrees C')
        print("Summer")
else:
    print('unliveable') #if we take real world condition countable


# If we just maintain question's given conditions

degrees_Fahrenheit=float(input('enter temperature in degrees Fahrenheit '))
degrees_Celsius = (degrees_Fahrenheit - 32) * 0.56

if (degrees_Celsius<20):
        print(degrees_Celsius ,'degrees C')
        print("Winter")
elif (degrees_Celsius>=20 and degrees_Celsius<=25):
        print(degrees_Celsius ,'degrees C')
        print("Autumn")

elif (degrees_Celsius>25 and degrees_Celsius<30):
        print(degrees_Celsius ,'degrees C')
        print("Spring")

else:
        print(degrees_Celsius ,'degrees C')
        print("Summer")

"""### Task 15
Suppose, your friend is building an automated car called “Besla”. He needs to fix the programming of the car so that it runs at a proper speed. Now, write a python program that takes 2 inputs (distance in meters and time in seconds). The program should then print the velocity in kilometers per hour of that car. Also, it should print whether the car is working properly based on the following chart.

|Velocity|Information to be printed|
|------|------|
|Less than 60 km/h  |Too slow. Needs more changes.
|Between 60 km/h to 90 km/h |Velocity is okay. The car is ready!
|Greater than 90 km/h|Too fast. Only a few changes should suffice.

==========================================

**Sample Input 1:**\
160000\
7200


**Sample Output 1:**\
80.0 km/h\
Velocity is okay. The car is ready!


**Explanation:** After the conversion of distance and time, the velocity is (160/2) km/h = 80 km/h. So the velocity is okay

 ==========================================

**Sample Input 2:**\
25400\
3600


**Sample Output 2:**\
25.4 km/h\
Too slow. Needs more changes.

**Explanation:** After the conversion of distance and time, the velocity is (25.4/1) km/h = 25.4 km/h. So the speed is too slow.
"""

#todo
d= float(input('enter metre distance covered by Besla '))
t= float(input('enter second taken by Besla to cover distance '))
# t can't be zero or negative

v=(d/1000)/(t/3600)
if (v>0):
    if (v<60):
        print(v,'km/h')
        print('Too slow.Needs more changes.')
    elif(v>=60 and v<=90):
        print(v,'km/h')
        print('Velocity is okay.The car is ready.')
    else:
        print(v,'km/h')
        print('Too fast.Only a few changes should suffice.')
elif (v==0):
    print(v,'km/h')
    print('You have not moved yet to find the velocity.')
else:
    print('invalid input')

"""### Task 16
Write a python program that takes the CGPA and no of credits completed by a student and prints whether the student is eligible for a waiver and of what percentage.

To be eligible for a waiver, a student must have completed at least 30 credits and earned a CGPA greater or equal to 3.8. If not, please print "The students is not eligible for a waiver".

**CGPA** | **Waiver percentage**
--- | ---
3.80 - 3.89 | 25 percent
3.90 - 3.94 | 50 percent
3.95 - 3.99 | 75 percent
4.00 | 100 percent


**Sample Input 1:** \
3.93 \
78

**Sample Output 1:**\
The student is eligible for a waiver of 50 percent.

================================================================================

**Sample Input 2:** \
3.79 \
24

**Sample Output 2:**\
The students is not eligible for a waiver \

"""

#todo
cgpa_entry=float(input('enter your obtained CGPA'))
cgpa=round(cgpa_entry,2)
#rounding up someone's cgpa to 2 decimal places

credits=int(input('Enter your completed credits '))



if (credits>=30 and cgpa>=3.8 and cgpa<=4):
    if(cgpa<=3.89):
        print('The student is eligible for a waiver of 25 percent')
    elif(cgpa>=3.90 and cgpa<=3.94):
        print('The student is eligible for a waiver of 50 percent')
    elif(cgpa>=3.95 and cgpa<=3.99):
        print('The student is eligible for a waiver of 75 percent')
    else:
        print('The student is eligible for a waiver of 100 percent')
elif(cgpa<0):
     print('cgpa can not be negative.')
elif(cgpa>4):
     print('invalid input')

else:
     print('The students is not eligible for a waiver.')

"""## Optional Tasks (17 - 19) [Ungraded]

**These tasks are just for practice. No marks will be deducted for not completing them and no bonus marks will be given for solving them. Just try and practice these problems.**

### Task 17

Write the Python code of a program that reads an integer, and prints the integer if it is a multiple of **NEITHER 2 NOR 5.**

For example, 1, 3, 7, 9, 11, 13, 17, 19, 21, 23, 27, 29, 31, 33, 37, 39 …

==========================================================

*hint(1): you may use the modulus (%) operator for checking the divisibility*

*hint(2): you can consider the number to be an integer*


==========================================================

**Sample Input 1:** \
3

**Sample Output 1:** \
3


==========================================================


**Sample Input 2:** \
19

**Sample Output 2:** \
19

==========================================================


**Sample Input 3:** \
5

**Sample Output 3:** \
No

==========================================================


**Sample Input 4:** \
12

**Sample Output 4:** \
No
"""

#todo

"""### Task 18

Write the Python code of a program that reads an integer, and prints the integer if it is **NOT a multiple of 2** OR **NOT a multiple of 5.**

For example, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22

==========================================================

*hint(1): you may use the modulus (%) operator for checking the divisibility*

*hint(2): you can consider the number to be an integer*


==========================================================

**Sample Input 1:** \
3

**Sample Output 1:** \
3

==========================================================

**Sample Input 2:** \
15

**Sample Output 2:** \
15

==========================================================

**Sample Input 3:** \
20

**Sample Output 3:** \
No

==========================================================

**Sample Input 4:** \
14

**Sample Output 4:** \
14
"""

#todo

"""### Task 19
Fiona has recently started acrylic painting and she is planning to order a few canvases and paints from an online stationery shop. The price of each 10 x 10 sized canvas is **120 tk** and the price of each 25 ml paint tube is **75 tk**. Depending on the total amount ordered from the shop, she will get some discounts. The table below shows the discount she will get on her total amount.


|Total Amount (TK)|Discount (TK)|
|------|------|
|0 - 299|No Discount|
|300 - 499|10|
|500 - 749 |20|
|750 - 999|50|
|>= 1000|150|

Write a python program and take two inputs from the user. The first input will be the number of canvases and the second input will be the number of paint tubes ordered. Based on the price of each item, calculate the total amount that Fiona needs to pay including the discount.

 ================================


**Sample Input 1:**\
5\
8


**Sample Output 1:**\
Previous total: 1200\
New total after discount: 1050


**Explanation:** 5 * 120 + 8 * 75 = 1200 Tk was her bill without discount.  For 1200 Tk, the discount amount is 150 Tk. So, her new bill with a discount is (1200 - 150) = 1050 Tk.

================================

**Sample Input 2:**\
0\
3


**Sample Output 2:**\
Previous total: 225\
New total after discount: 225



**Explanation:** 0 * 120 + 3 * 75 = 225 Tk was her bill without discount.  For 225 Tk, the discount amount is 0 Tk. So, her new bill with a discount is (225 - 0) = 225 Tk.

"""

#todo